spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yes2
    username: postgres
    password: "911a"

## Hibernate properties
#  spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
#  spring.jpa.show-sql = false
#  spring.jpa.hibernate.ddl-auto = create-drop
#  spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#  spring.jpa.properties.hibernate.format_sql=true

title:
  message: Prod Title
